// src/components/Movie/Tabs.vue
<script setup lang="ts">
import { ref } from 'vue';
import { ElTabs, ElTabPane } from 'element-plus';
let cates = ref({
    hot: '热映',
    comming: '即将上映',
    expceted: '最期待',
    class: '经典'
});
let active = ref('hot');
</script>
<template>
    <ElTabs v-model="active">
        <ElTabPane v-for="(cate, key) in cates" :key="key" :name="key" :label="cate"></ElTabPane>
</ElTabs>
</template>

// src/components/Movie/Tabs.tsx
import { Tabs } from 'antd'
import { useState, useEffect } from 'react'
// let cates = {
//     hot: '热映',
//     comming: '即将上映',
//     expceted: '最期待',
//     class: '经典'
// };
let cates = [
    {
        key: 'hot',
        label: '热映',
    },
    {
        key: 'coming',
        label: '即将上映',
    },
    {
        key: 'expected',
        label: '最期待',
    },
    {
        key: 'class',
        label: '经典',
    },
]
export default () => {
    const [active, setActive] = useState('hot')
    useEffect(() => {
        const params = new URLSearchParams(window.location.search);
        setActive(params.get('type') || 'hot')
    }, [])
    const onChange = (key:string) => {
        window.location.replace(`/movie?type=${key}`)
        // setActive(key)
    }
    return (
        <Tabs activeKey={active} defaultActiveKey="hot" items={cates} onChange={onChange}>
        </Tabs>
    )
}
